# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    bulkOperations/master:
      - step:
          caches:
            - node
          name: Build and Test
          script:
            - echo 'Build and Test...'
    bulkOperations/dev:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - echo "Build and test..."
