version: '3.7'
services:
  addon:
    container_name: cloudBackupAddOn
    shm_size: '500Mb'
    image: node:13.10.1-alpine3.10
    volumes:
      - '../_cloud-backup-add-on/:/addon'
    working_dir: /addon
    command: node scripts/server.js
    networks:
      - api

  graphql:
    container_name: cloudBackupGraphql
    shm_size: '500Mb'
    image: node:13.10.1-alpine3.10
    volumes:
      - '../:/api/graphql'
    working_dir: /api/graphql
    command: npm run cloudBackupApi.build.docker
    expose:
      - '4000'
    networks:
      - api
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: cloudBackupDynamodb
    environment:
      - ./Djava.library.path=./DynamoDBLocal_lib
    volumes:
      - .:/data/dynamodb-seed
    ports:
      - 8001:8000
    networks:
      - api
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-dbPath', './', '-cors', '*']

  nginx:
    image: nginx:latest
    container_name: cloudBackupApiGateway
    depends_on:
      - graphql
    volumes:
      - ./nginx-apigateway.conf:/etc/nginx/nginx.conf
    networks:
      - api
    ports:
      - 8080:8080

networks:
  api:
    # use the bridge driver, but enable IPv6
    driver: bridge
